# Generated by Django 5.0.6 on 2024-06-19 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_userinformation_bloodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='bloodType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='database.bloodtype'),
        ),
    ]
